// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectEditor.Persistence.Repositories.DBContext;

namespace ProjectEditor.Persistence.Migrations
{
    [DbContext(typeof(ProjectEditorDbContext))]
    [Migration("20220603214844_added location and function with corrections")]
    partial class addedlocationandfunctionwithcorrections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjectEditor.Core.Entities.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a81c327-07a9-4b1d-a400-222b785f6481"),
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 170, DateTimeKind.Local).AddTicks(4156),
                            CreatedBy = "Created via DbContext",
                            Name = "DummyCustomer Mani & Friends"
                        },
                        new
                        {
                            Id = new Guid("02d2f7a4-8c6e-4f2e-873e-7edc45314939"),
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 174, DateTimeKind.Local).AddTicks(64),
                            CreatedBy = "Created via DbContext",
                            Name = "DummyCustomer Hudli und Murks"
                        },
                        new
                        {
                            Id = new Guid("651dd1b3-5abe-4884-9be8-59338c6165c8"),
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 174, DateTimeKind.Local).AddTicks(107),
                            CreatedBy = "Created via DbContext",
                            Name = "DummyCustomer Blue Monday"
                        });
                });

            modelBuilder.Entity("ProjectEditor.Core.Entities.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInSchematic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93752f09-7eb5-4d1c-8c25-b744a5c4dbbe"),
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(8978),
                            CreatedBy = "Created via DbContext",
                            Name = "DummyDevice A via DbContext",
                            NameInSchematic = "-K300",
                            ProjectId = new Guid("ed9c66c8-e2eb-4764-b625-96657b603d25")
                        },
                        new
                        {
                            Id = new Guid("c5d683d9-f1f2-4c7a-9f3a-857ab00f2105"),
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(9276),
                            CreatedBy = "Created via DbContext",
                            Name = "DummyDevice B via DbContext",
                            NameInSchematic = "-S200",
                            ProjectId = new Guid("087b0654-c840-43a2-b827-90d47c5ba041")
                        },
                        new
                        {
                            Id = new Guid("d4d2cf99-99f1-4e29-b429-c03a6f1ff492"),
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(9296),
                            CreatedBy = "Created via DbContext",
                            Name = "DummyDevice C via DbContext",
                            NameInSchematic = "-K100",
                            ProjectId = new Guid("fe04d159-3cd6-4a19-a53e-48ab4425b5fd")
                        });
                });

            modelBuilder.Entity("ProjectEditor.Core.Entities.Projects.Function", b =>
                {
                    b.Property<string>("NameInSchematic")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NameInSchematic");

                    b.HasIndex("ProjectId");

                    b.ToTable("Functions");

                    b.HasData(
                        new
                        {
                            NameInSchematic = "=Dummy.hmb",
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(6906),
                            CreatedBy = "Created via DbContext",
                            Description = "hold my beer",
                            ProjectId = new Guid("ed9c66c8-e2eb-4764-b625-96657b603d25")
                        },
                        new
                        {
                            NameInSchematic = "=Dummy.dOtT",
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(7191),
                            CreatedBy = "Created via DbContext",
                            Description = "dancing on the table",
                            ProjectId = new Guid("087b0654-c840-43a2-b827-90d47c5ba041")
                        },
                        new
                        {
                            NameInSchematic = "=Dummy.SUPER",
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(7208),
                            CreatedBy = "Created via DbContext",
                            Description = "execute supernova",
                            ProjectId = new Guid("fe04d159-3cd6-4a19-a53e-48ab4425b5fd")
                        });
                });

            modelBuilder.Entity("ProjectEditor.Core.Entities.Projects.Location", b =>
                {
                    b.Property<string>("NameInSchematic")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NameInSchematic");

                    b.HasIndex("ProjectId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            NameInSchematic = "+Dummy.LocA",
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(5244),
                            CreatedBy = "Created via DbContext",
                            Description = "6 feet under",
                            ProjectId = new Guid("ed9c66c8-e2eb-4764-b625-96657b603d25")
                        },
                        new
                        {
                            NameInSchematic = "+Dummy.LocB",
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(5548),
                            CreatedBy = "Created via DbContext",
                            Description = "up in sky",
                            ProjectId = new Guid("087b0654-c840-43a2-b827-90d47c5ba041")
                        },
                        new
                        {
                            NameInSchematic = "+Dummy.LocC",
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(5567),
                            CreatedBy = "Created via DbContext",
                            Description = "6 feet under",
                            ProjectId = new Guid("fe04d159-3cd6-4a19-a53e-48ab4425b5fd")
                        });
                });

            modelBuilder.Entity("ProjectEditor.Core.Entities.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed9c66c8-e2eb-4764-b625-96657b603d25"),
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(3583),
                            CreatedBy = "Created via DbContext",
                            CustomerId = new Guid("2a81c327-07a9-4b1d-a400-222b785f6481"),
                            Name = "TimeControl 2.1",
                            ProjectManagerName = "Nero"
                        },
                        new
                        {
                            Id = new Guid("087b0654-c840-43a2-b827-90d47c5ba041"),
                            Created = new DateTime(2022, 6, 3, 23, 48, 44, 175, DateTimeKind.Local).AddTicks(3930),
                            CreatedBy = "Created via DbContext",
                            CustomerId = new Guid("02d2f7a4-8c6e-4f2e-873e-7edc45314939"),
                            Name = "WeatherChanger V1.0",
                            ProjectManagerName = "Montgomery Burns"
                        },
                        new
                        {
                            Id = new Guid("fe04d159-3cd6-4a19-a53e-48ab4425b5fd"),
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "Created via DbContext",
                            CustomerId = new Guid("651dd1b3-5abe-4884-9be8-59338c6165c8"),
                            Name = "Water2Wine Vers.A",
                            ProjectManagerName = "Queen Mary"
                        });
                });

            modelBuilder.Entity("ProjectEditor.Core.Entities.Devices.Device", b =>
                {
                    b.HasOne("ProjectEditor.Core.Entities.Projects.Project", "Project")
                        .WithMany("Devices")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectEditor.Core.Entities.Projects.Function", b =>
                {
                    b.HasOne("ProjectEditor.Core.Entities.Projects.Project", "Project")
                        .WithMany("Functions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectEditor.Core.Entities.Projects.Location", b =>
                {
                    b.HasOne("ProjectEditor.Core.Entities.Projects.Project", "Project")
                        .WithMany("Locations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectEditor.Core.Entities.Projects.Project", b =>
                {
                    b.HasOne("ProjectEditor.Core.Entities.Customers.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
